// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReserGo.DataAccess;

#nullable disable

namespace ReserGo.DataAccess.Migrations
{
    [DbContext(typeof(ReserGoContext))]
    [Migration("20250516140543_book restaurant")]
    partial class bookrestaurant
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReserGo.Common.Entity.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("ReserGo.Common.Entity.BookingHotel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("HotelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HotelOfferId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("HotelOfferId");

                    b.HasIndex("UserId");

                    b.ToTable("BookingHotel");
                });

            modelBuilder.Entity("ReserGo.Common.Entity.BookingOccasion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OccasionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("VipAccess")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("OccasionId");

                    b.HasIndex("UserId");

                    b.ToTable("BookingOccasion");
                });

            modelBuilder.Entity("ReserGo.Common.Entity.BookingRestaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RestaurantOfferId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("RestaurantOfferId");

                    b.HasIndex("UserId");

                    b.ToTable("BookingRestaurant");
                });

            modelBuilder.Entity("ReserGo.Common.Entity.Hotel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Picture")
                        .HasColumnType("text");

                    b.Property<long>("StayId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StayId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Hotel");
                });

            modelBuilder.Entity("ReserGo.Common.Entity.HotelOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfRooms")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OfferEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OfferStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OfferTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PricePerNight")
                        .HasColumnType("double precision");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("UserId");

                    b.ToTable("HotelOffer");
                });

            modelBuilder.Entity("ReserGo.Common.Entity.Login", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Login");
                });

            modelBuilder.Entity("ReserGo.Common.Entity.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ReserGo.Common.Entity.Occasion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Picture")
                        .HasColumnType("text");

                    b.Property<long>("StayId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StayId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Occasion");
                });

            modelBuilder.Entity("ReserGo.Common.Entity.OccasionOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("integer");

                    b.Property<Guid>("OccasionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OfferEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OfferStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OfferTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OccasionId");

                    b.HasIndex("UserId");

                    b.ToTable("OccasionOffer");
                });

            modelBuilder.Entity("ReserGo.Common.Entity.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("CuisineType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Picture")
                        .HasColumnType("text");

                    b.Property<long>("StayId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StayId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Restaurant");
                });

            modelBuilder.Entity("ReserGo.Common.Entity.RestaurantOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OfferEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OfferStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OfferTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("PricePerPerson")
                        .HasColumnType("double precision");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("UserId");

                    b.ToTable("RestaurantOffer");
                });

            modelBuilder.Entity("ReserGo.Common.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ReserGo.Common.Entity.Address", b =>
                {
                    b.HasOne("ReserGo.Common.Entity.User", "User")
                        .WithOne("Address")
                        .HasForeignKey("ReserGo.Common.Entity.Address", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReserGo.Common.Entity.BookingHotel", b =>
                {
                    b.HasOne("ReserGo.Common.Entity.Hotel", null)
                        .WithMany("BookingsHotel")
                        .HasForeignKey("HotelId");

                    b.HasOne("ReserGo.Common.Entity.HotelOffer", "HotelOffer")
                        .WithMany("Bookings")
                        .HasForeignKey("HotelOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReserGo.Common.Entity.User", "User")
                        .WithMany("BookingsHotel")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HotelOffer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReserGo.Common.Entity.BookingOccasion", b =>
                {
                    b.HasOne("ReserGo.Common.Entity.Occasion", "Occasion")
                        .WithMany("BookingsOccasion")
                        .HasForeignKey("OccasionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReserGo.Common.Entity.User", "User")
                        .WithMany("BookingsOccasion")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Occasion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReserGo.Common.Entity.BookingRestaurant", b =>
                {
                    b.HasOne("ReserGo.Common.Entity.Restaurant", null)
                        .WithMany("BookingRestaurant")
                        .HasForeignKey("RestaurantId");

                    b.HasOne("ReserGo.Common.Entity.RestaurantOffer", "RestaurantOffer")
                        .WithMany("Bookings")
                        .HasForeignKey("RestaurantOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReserGo.Common.Entity.User", "User")
                        .WithMany("BookingsRestaurant")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RestaurantOffer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReserGo.Common.Entity.Hotel", b =>
                {
                    b.HasOne("ReserGo.Common.Entity.User", "User")
                        .WithMany("Hotels")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReserGo.Common.Entity.HotelOffer", b =>
                {
                    b.HasOne("ReserGo.Common.Entity.Hotel", "Hotel")
                        .WithMany("HotelOffers")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReserGo.Common.Entity.User", "User")
                        .WithMany("HotelOffers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReserGo.Common.Entity.Login", b =>
                {
                    b.HasOne("ReserGo.Common.Entity.User", "User")
                        .WithOne("Login")
                        .HasForeignKey("ReserGo.Common.Entity.Login", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReserGo.Common.Entity.Notification", b =>
                {
                    b.HasOne("ReserGo.Common.Entity.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReserGo.Common.Entity.Occasion", b =>
                {
                    b.HasOne("ReserGo.Common.Entity.User", "User")
                        .WithMany("Occasions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReserGo.Common.Entity.OccasionOffer", b =>
                {
                    b.HasOne("ReserGo.Common.Entity.Occasion", "Occasion")
                        .WithMany("OccasionOffers")
                        .HasForeignKey("OccasionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReserGo.Common.Entity.User", "User")
                        .WithMany("OccasionOffers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Occasion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReserGo.Common.Entity.Restaurant", b =>
                {
                    b.HasOne("ReserGo.Common.Entity.User", "User")
                        .WithMany("Restaurants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReserGo.Common.Entity.RestaurantOffer", b =>
                {
                    b.HasOne("ReserGo.Common.Entity.Restaurant", "Restaurant")
                        .WithMany("RestaurantOffers")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReserGo.Common.Entity.User", "User")
                        .WithMany("RestaurantOffers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReserGo.Common.Entity.Hotel", b =>
                {
                    b.Navigation("BookingsHotel");

                    b.Navigation("HotelOffers");
                });

            modelBuilder.Entity("ReserGo.Common.Entity.HotelOffer", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("ReserGo.Common.Entity.Occasion", b =>
                {
                    b.Navigation("BookingsOccasion");

                    b.Navigation("OccasionOffers");
                });

            modelBuilder.Entity("ReserGo.Common.Entity.Restaurant", b =>
                {
                    b.Navigation("BookingRestaurant");

                    b.Navigation("RestaurantOffers");
                });

            modelBuilder.Entity("ReserGo.Common.Entity.RestaurantOffer", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("ReserGo.Common.Entity.User", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("BookingsHotel");

                    b.Navigation("BookingsOccasion");

                    b.Navigation("BookingsRestaurant");

                    b.Navigation("HotelOffers");

                    b.Navigation("Hotels");

                    b.Navigation("Login")
                        .IsRequired();

                    b.Navigation("Notifications");

                    b.Navigation("OccasionOffers");

                    b.Navigation("Occasions");

                    b.Navigation("RestaurantOffers");

                    b.Navigation("Restaurants");
                });
#pragma warning restore 612, 618
        }
    }
}
